# Generated by Django 5.0.4 on 2024-04-18 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil_usuario', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='usu_senha',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='usu_perfil',
            field=models.ForeignKey(db_column='per_id', on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='perfil_usuario.perfilusuario'),
        ),
    ]
