# Generated by Django 5.0.4 on 2024-04-29 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'Usuário', 'verbose_name_plural': 'Usuários'},
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='usu_nome',
        ),
        migrations.AddField(
            model_name='usuario',
            name='usu_nome_completo',
            field=models.CharField(default='Nome Usuário Padrão', max_length=255, verbose_name='Nome Completo'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='usu_usuario',
            field=models.CharField(default='usuario_padrao', max_length=100, unique=True, verbose_name='Nome de Usuário'),
        ),
    ]
