# Generated by Django 5.0.4 on 2024-05-01 01:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil_usuario', '0001_initial'),
        ('usuarios', '0002_alter_usuario_options_remove_usuario_usu_nome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='usu_perfil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfil_usuario.perfilusuario'),
        ),
    ]
