# Generated by Django 5.0.4 on 2024-05-01 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_remove_usuario_usu_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='usu_perfil',
            field=models.CharField(default=1, max_length=100, verbose_name='Perfil do Usuário'),
        ),
    ]
