# Generated by Django 5.0.4 on 2024-04-18 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('per_id', models.AutoField(primary_key=True, serialize=False)),
                ('per_nome', models.CharField(max_length=100)),
                ('per_data_criacao', models.DateTimeField(auto_now_add=True)),
                ('per_data_alteracao', models.DateTimeField(auto_now=True)),
                ('per_data_exclusao', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tb_perfil_usuarios',
            },
        ),
    ]
