# Generated by Django 5.0.4 on 2024-04-19 18:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('cur_id', models.AutoField(primary_key=True, serialize=False)),
                ('cur_ativo', models.BooleanField(default=True)),
                ('cur_titulo', models.CharField(max_length=100)),
                ('cur_descricao', models.TextField()),
                ('cur_carga_horaria', models.IntegerField()),
                ('cur_valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cur_data_inicio', models.DateField(default=django.utils.timezone.now)),
                ('cur_data_fim', models.DateField()),
                ('cur_data_criacao', models.DateTimeField(auto_now_add=True)),
                ('cur_data_alteracao', models.DateTimeField(auto_now=True)),
                ('cur_data_exclusao', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tb_cursos',
            },
        ),
    ]
