# Generated by Django 5.0.4 on 2024-04-17 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ativo', models.BooleanField(default=True)),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('carga_horaria', models.IntegerField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
            ],
        ),
    ]
