# Generated by Django 5.0.4 on 2024-04-17 21:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curso',
            old_name='ativo',
            new_name='cur_ativo',
        ),
        migrations.RenameField(
            model_name='curso',
            old_name='carga_horaria',
            new_name='cur_carga_horaria',
        ),
        migrations.RenameField(
            model_name='curso',
            old_name='descricao',
            new_name='cur_descricao',
        ),
        migrations.RenameField(
            model_name='curso',
            old_name='id',
            new_name='cur_id',
        ),
        migrations.RenameField(
            model_name='curso',
            old_name='titulo',
            new_name='cur_titulo',
        ),
        migrations.RenameField(
            model_name='curso',
            old_name='valor',
            new_name='cur_valor',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='data_fim',
        ),
        migrations.AddField(
            model_name='curso',
            name='cur_data_alteracao',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='cur_data_criacao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='curso',
            name='cur_data_exclusao',
            field=models.DateTimeField(null=True),
        ),
    ]
