# Generated by Django 5.0.4 on 2024-04-17 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0003_curso_teste'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='teste',
        ),
        migrations.AlterModelTable(
            name='curso',
            table='tb_cursos',
        ),
    ]
