# Generated by Django 5.0.4 on 2024-04-18 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0004_remove_curso_teste_alter_curso_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='cur_data_exclusao',
        ),
        migrations.AddField(
            model_name='curso',
            name='cur_data_exclusaeeo',
            field=models.DateTimeField(null=True),
        ),
    ]
