# Generated by Django 5.0.4 on 2024-04-18 15:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0005_remove_curso_cur_data_exclusao_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curso',
            old_name='data_inicio',
            new_name='cur_data_fim',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='cur_data_exclusaeeo',
        ),
        migrations.AddField(
            model_name='curso',
            name='cur_data_exclusao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='cur_data_inicio',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='curso',
            name='cur_data_alteracao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='cur_data_criacao',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
