# Generated by Django 5.0.4 on 2024-04-24 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscricao_cursos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscricaocurso',
            name='ins_tipo_alergia',
            field=models.TextField(blank=True, null=True),
        ),
    ]
