name: backend CI/CD

on:
  push:
    branches:
      - producaoApis

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.3' 

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r apisGabiMakeup/requeriments.txt

    - name: Run tests
      run: |
        python apisGabiMakeup/manage.py test  
